name: hidapi_dart
description: |
  This package is a thin layer of ffi interface to hidapi library.
  Built for communiating with hid devices.
version: 0.0.10
homepage: https://github.com/Nightfeather/hidapi_dart

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
