name: hidapi_dart
description: |
  This package is a thin layer of ffi interface to hidapi library.
  Built for communiating with hid devices.
version: 0.0.6
author: Nightfeather
homepage: https://github.com/Nightfeather/hidapi_dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ffi: ^0.1.3
